models:
  - name: "btc_1d_from_8h"
    pair: "BTC-USD"
    predict_timeframe: "1d"  # predict 1 day
    input_timeframe: "8h"    # using last 8 hours of data

  - name: "btc_1w_from_8h"
    pair: "BTC-USD"
    predict_timeframe: "1w"  # predict 1 week ahead
    input_timeframe: "8h"    # using last 8 hours of data

  - name: "btc_1m_from_7d"
    pair: "BTC-USD"
    predict_timeframe: "1m"  # predict 1 month ahead
    input_timeframe: "7d"    # using last 7 days of data

  - name: "btc_3m_from_7d"
    pair: "BTC-USD"
    predict_timeframe: "3m"  # predict 3 months ahead
    input_timeframe: "7d"    # using last 7 days of data

  - name: "eth_1d_from_8h"
    pair: "ETH-USD"
    predict_timeframe: "1d"  # predict 1 day
    input_timeframe: "8h"    # using last 8 hours of data

  - name: "eth_1w_from_8h"
    pair: "ETH-USD"
    predict_timeframe: "1w"  # predict 1 week ahead
    input_timeframe: "8h"    # using last 8 hours of data

  - name: "eth_1m_from_7d"
    pair: "ETH-USD"
    predict_timeframe: "1m"  # predict 1 month ahead
    input_timeframe: "7d"    # using last 7 days of data

  - name: "eth_3m_from_7d"
    pair: "ETH-USD"
    predict_timeframe: "3m"  # predict 3 months ahead
    input_timeframe: "7d"    # using last 7 days of data