# Use the official Python image from the Docker Hub
FROM python:3.12.3

# Set environment variables
ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

# Create and set the working directory in the container
WORKDIR /app

# Copy the requirements file into the container
COPY requirements.txt /app/

# Install the dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Copy the rest of the application into the container
COPY . /app/

# Healthcheck to clean files older than 4 hours in /tmp every 30 minutes
HEALTHCHECK --interval=30m CMD find /tmp -mindepth 1 -mmin +240 -exec rm -rf {} \; || exit 0

# Run the application
CMD ["python", "-m", "app.cache.cache_price_worker"]
